apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: borderleaf1-ethernet-1-31
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: borderleaf1-ethernet-1-32
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: borderleaf2-ethernet-1-31
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: borderleaf2-ethernet-1-32
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf1-ethernet-1-31
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf1-ethernet-1-32
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf2-ethernet-1-31
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf2-ethernet-1-32
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf3-ethernet-1-31
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf3-ethernet-1-32
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-ethernet-1-1
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-ethernet-1-2
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-ethernet-1-3
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-ethernet-1-4
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-ethernet-1-5
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-ethernet-1-1
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-ethernet-1-2
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-ethernet-1-3
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-ethernet-1-4
  namespace: eda
spec:
  mtu: 9198
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-ethernet-1-5
  namespace: eda
spec:
  mtu: 9198
---
