apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: edge
  name: leaf1-ethernet-1-1
  namespace: eda
spec:
  description: edge link to client1
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-1
    lacpPortPriority: 32768
    node: leaf1
  type: interface
---
alarms:
  critical: 1
  major: 0
  minor: 0
  warning: 0
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: edge
  name: leaf1-ethernet-1-2
  namespace: eda
spec:
  description: edge link to client2
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-2
    lacpPortPriority: 32768
    node: leaf1
  type: interface
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: edge
  name: leaf2-ethernet-1-1
  namespace: eda
spec:
  description: edge link to client2
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-1
    lacpPortPriority: 32768
    node: leaf2
  type: interface
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: edge
  name: leaf3-ethernet-1-1
  namespace: eda
spec:
  description: edge link to client3
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-1
    lacpPortPriority: 32768
    node: leaf3
  type: interface
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: edge
  name: leaf3-ethernet-1-2
  namespace: eda
spec:
  description: edge link to client4
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-2
    lacpPortPriority: 32768
    node: leaf3
  type: interface